import type { LucideIcon } from 'lucide-react';
import {
  AlarmClock,
  AlertTriangle,
  Apple,
  AtSign,
  Award,
  Banknote,
  BarChart3,
  CalendarRange,
  Bell,
  Bike,
  BookCopy,
  BookMarked,
  BookOpen,
  Briefcase,
  Bug,
  Building2,
  CalendarDays,
  Camera,
  CircleAlert,
  ClipboardCheck,
  ClipboardList,
  Code,
  Coffee,
  Database,
  DoorOpen,
  Drama,
  Droplets,
  Dumbbell,
  FileBarChart,
  FileSpreadsheet,
  Flag,
  Flame,
  FlaskConical,
  Gamepad2,
  Glasses,
  Globe,
  GraduationCap,
  Hammer,
  HandHeart,
  Headphones,
  Heart,
  HeartPulse,
  IceCream,
  IdCard,
  KeyRound,
  Languages,
  Laptop,
  Layers,
  Library,
  Megaphone,
  MessageCircle,
  MessageCircleQuestion,
  Mic2,
  Monitor,
  Music,
  Palette,
  Phone,
  Presentation,
  Printer,
  Projector,
  QrCode,
  Rocket,
  Router,
  Sandwich,
  Scissors,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  Stethoscope,
  Ticket,
  TrendingUp,
  Trophy,
  UploadCloud,
  UserCog,
  UserRound,
  Users,
  Utensils,
  Video,
  Volleyball,
  Wallet,
  Wifi,
  ShieldAlert,
  BadgeCheck,
} from 'lucide-react';
import type { SectionFeed } from './types';

const icon = (Icon: LucideIcon) => Icon;

export const SECTION_DATA: Record<string, SectionFeed> = {
  /* ------------------------------- Overview ------------------------------ */
  schedule: {
    description: 'Your weekly class timetable with rooms and lecturers.',
    items: [
      {
        id: 'sched-mon',
        icon: icon(BookOpen),
        title: 'Monday',
        description: 'Software Engineering Fundamentals · CSE 101',
        meta: ['09:00 – 10:30', 'Dr. Sanjaya Silva'],
        tags: ['Lecture'],
      },
      {
        id: 'sched-tue',
        icon: icon(FlaskConical),
        title: 'Tuesday',
        description: 'Database Systems Lab · Lab 4',
        meta: ['11:00 – 12:30', 'Ms. Tharushi Weerasinghe'],
        tags: ['Lab'],
      },
      {
        id: 'sched-wed',
        icon: icon(ClipboardList),
        title: 'Wednesday',
        description: 'Data Structures & Algorithms · CSE 305',
        meta: ['13:30 – 15:00', 'Dr. Kasun Jayasuriya'],
        tags: ['Tutorial'],
      },
      {
        id: 'sched-thu',
        icon: icon(Users),
        title: 'Thursday',
        description: 'Group project workshop · Innovation Hub',
        meta: ['10:00 – 12:00', 'Facilitator: Academic Office'],
        tags: ['Workshop'],
      },
      {
        id: 'sched-fri',
        icon: icon(Monitor),
        title: 'Friday',
        description: 'Free study period — no scheduled sessions',
        meta: ['Full day'],
        tags: ['Study'],
      },
    ],
  },
  courses: {
    description: 'Your enrolled modules, progress and key resources.',
    items: [
      {
        id: 'cse2201',
        icon: icon(GraduationCap),
        title: 'Software Engineering Fundamentals',
        subtitle: 'CSE2201 · 5 credits',
        description: 'Requirements, design, sprints and agile delivery.',
        meta: ['68% complete', 'Assignment due today'],
        tags: ['Core'],
        action: 'interest',
        count: 42,
      },
      {
        id: 'cse2202',
        icon: icon(Database),
        title: 'Database Systems',
        subtitle: 'CSE2202 · 5 credits',
        description: 'ER modelling, SQL and normalisation.',
        meta: ['54% complete', 'Lab report due Fri'],
        tags: ['Core'],
        action: 'interest',
        count: 35,
      },
      {
        id: 'cse2203',
        icon: icon(Layers),
        title: 'Data Structures & Algorithms',
        subtitle: 'CSE2203 · 4 credits',
        description: 'Trees, graphs, sorting and complexity analysis.',
        meta: ['41% complete', 'Quiz next week'],
        tags: ['Core'],
        action: 'interest',
        count: 28,
      },
      {
        id: 'csemgmt',
        icon: icon(BarChart3),
        title: 'Engineering Management',
        subtitle: 'MGT3301 · 3 credits',
        description: 'Project planning, budgeting and team leadership.',
        meta: ['Enrolled', 'Starts week 10'],
        tags: ['Elective'],
        action: 'interest',
        count: 19,
      },
    ],
  },
  assignments: {
    description: 'Everything you need to submit, with clear deadlines.',
    items: [
      {
        id: 'asg-sweng',
        icon: icon(ClipboardCheck),
        title: 'Assignment 2 – Sprint review',
        description: 'Submit your sprint board and retrospective.',
        meta: ['Due today 17:55', 'Weight 25%'],
        tags: ['Software Eng.'],
      },
      {
        id: 'asg-db',
        icon: icon(FileSpreadsheet),
        title: 'ERD + normalisation worksheet',
        description: 'Complete the worksheet and upload your diagrams.',
        meta: ['Fri, 22 Sep · 23:59', 'Weight 15%'],
        tags: ['Database'],
      },
      {
        id: 'asg-dsa',
        icon: icon(Code),
        title: 'AVL tree implementation',
        description: 'Implement insert, delete and rotations in C++.',
        meta: ['Mon, 25 Sep · 09:00', 'Weight 20%'],
        tags: ['Data Structures'],
      },
      {
        id: 'asg-sa',
        icon: icon(FileBarChart),
        title: 'Statement of intent',
        description: 'One-paragraph overview of your final project.',
        meta: ['Wed, 27 Sep · 23:59', 'Weight 5%'],
        tags: ['Final project'],
      },
    ],
  },
  recordings: {
    description: 'Recorded lectures and catch-up sessions.',
    items: [
      {
        id: 'rec-1',
        icon: icon(Video),
        title: 'SEF Week 8 – Sprints & retrospectives',
        meta: ['49 min', 'Published 2 days ago'],
        tags: ['Software Eng.'],
      },
      {
        id: 'rec-2',
        icon: icon(Projector),
        title: 'DBS – Normalisation deep dive',
        meta: ['1 h 04 min', 'Published 3 days ago'],
        tags: ['Database'],
      },
      {
        id: 'rec-3',
        icon: icon(Presentation),
        title: 'DSA – Balanced trees',
        meta: ['52 min', 'Published last week'],
        tags: ['Data Structures'],
      },
    ],
  },
  profile: {
    description: 'Your identity details across the university.',
    items: [
      {
        id: 'prof-1',
        icon: icon(IdCard),
        title: 'Personal details',
        description: 'Name, date of birth, nationality and address.',
        meta: ['Up to date'],
        tags: ['Identity'],
        action: 'save',
      },
      {
        id: 'prof-2',
        icon: icon(AtSign),
        title: 'Contact information',
        description: 'Email, mobile number and emergency contact.',
        meta: ['2 items flagged'],
        tags: ['Contact'],
        action: 'save',
      },
      {
        id: 'prof-3',
        icon: icon(KeyRound),
        title: 'Login & security',
        description: 'Password, two-factor and active sessions.',
        meta: ['2FA enabled'],
        tags: ['Security'],
        action: 'save',
      },
      {
        id: 'prof-4',
        icon: icon(GraduationCap),
        title: 'Academic record',
        description: 'Transcript, modules and awards.',
        meta: ['Verified'],
        tags: ['Academic'],
        action: 'save',
      },
    ],
  },
  settings: {
    description: 'Preferences for how the portal looks and behaves.',
    items: [
      {
        id: 'set-1',
        icon: icon(Bell),
        title: 'Notifications',
        description: 'Choose which alerts you receive by email or in-app.',
        meta: ['Email + in-app'],
        tags: ['Preferences'],
      },
      {
        id: 'set-2',
        icon: icon(Palette),
        title: 'Appearance',
        description: 'Light, dark or system theme.',
        meta: ['Use system setting'],
        tags: ['Preferences'],
      },
      {
        id: 'set-3',
        icon: icon(Globe),
        title: 'Language & region',
        description: 'Display language and timezone.',
        meta: ['English (UK)'],
        tags: ['Preferences'],
      },
      {
        id: 'set-4',
        icon: icon(ShieldCheck),
        title: 'Privacy & consent',
        description: 'Data sharing and marketing preferences.',
        meta: ['View consent records'],
        tags: ['Privacy'],
      },
    ],
  },
  help: {
    description: 'Guides and contact options when you need a hand.',
    items: [
      {
        id: 'help-1',
        icon: icon(BookMarked),
        title: 'Getting started with the portal',
        description: 'A 10-minute walkthrough of the main features.',
        meta: ['5 min read'],
        tags: ['Guide'],
      },
      {
        id: 'help-2',
        icon: icon(Phone),
        title: 'IT helpdesk',
        description: 'Report login problems, Wi-Fi and hardware issues.',
        meta: ['Ext 4200', 'Mon–Fri 08:00–18:00'],
        tags: ['Support'],
      },
      {
        id: 'help-3',
        icon: icon(MessageCircle),
        title: 'Talk to the service desk',
        description: 'Chat with a human during support hours.',
        meta: ['Live chat', 'Avg. reply < 5 min'],
        tags: ['Support'],
      },
      {
        id: 'help-4',
        icon: icon(MessageCircleQuestion),
        title: 'Frequently asked questions',
        description: 'Answers to the most common questions.',
        meta: ['42 articles'],
        tags: ['Docs'],
      },
    ],
  },

  /* -------------------------- Campus services --------------------------- */
  bookings: {
    description: 'Book rooms, study spaces and campus facilities.',
    report: {
      label: 'Request a booking',
      title: 'New booking request',
      description: 'Request a space for your study group, committee or event.',
      itemLabel: 'Describe what you need',
    },
    items: [
      {
        id: 'bk-1',
        icon: icon(DoorOpen),
        title: 'Study room B-204',
        description: '4–6 person bookable study room.',
        meta: ['Available 10:00 – 12:00', '2nd floor, CSE Block'],
        tags: ['Self-study'],
        action: 'book',
        count: 12,
      },
      {
        id: 'bk-2',
        icon: icon(Projector),
        title: 'Seminar room CSE 101',
        description: 'Projector, whiteboard and 40 seats.',
        meta: ['Free after 16:00', 'CSE Block'],
        tags: ['Group work'],
        action: 'book',
        count: 8,
      },
      {
        id: 'bk-3',
        icon: icon(Building2),
        title: 'Auditorium — full day',
        description: 'Large venue for talks and events.',
        meta: ['Fri, 22 Sep', 'Main hall'],
        tags: ['Events'],
        action: 'book',
        count: 3,
      },
      {
        id: 'bk-4',
        icon: icon(Volleyball),
        title: 'Sports court (indoor)',
        description: 'Badminton pitch or half court.',
        meta: ['17:00 – 21:00', 'Sports Centre'],
        tags: ['Sports'],
        action: 'book',
        count: 21,
      },
    ],
  },
  dining: {
    description: 'Where to eat on campus, menus and hours.',
    items: [
      {
        id: 'din-1',
        icon: icon(Utensils),
        title: "Chef's Garden Cafe",
        description: 'Hot meals, rice & curry and grill counter.',
        meta: ['07:30 – 21:00', 'Ground floor, Student Centre'],
        tags: ['Hot meals'],
      },
      {
        id: 'din-2',
        icon: icon(Coffee),
        title: 'Brew House',
        description: 'Specialty coffee, pastries and light bites.',
        meta: ['07:00 – 22:00', 'Library concourse'],
        tags: ['Coffee'],
      },
      {
        id: 'din-3',
        icon: icon(Sandwich),
        title: 'Delis & wraps',
        description: 'Fresh sandwiches, salads and vegan bowls.',
        meta: ['11:00 – 19:00', 'CSE Block atrium'],
        tags: ['Lunch'],
      },
      {
        id: 'din-4',
        icon: icon(IceCream),
        title: 'Dessert Bar',
        description: 'Ice cream, cake and bubble tea.',
        meta: ['12:00 – 20:00', 'Student Centre, level 2'],
        tags: ['Treats'],
      },
      {
        id: 'din-5',
        icon: icon(Apple),
        title: 'Tuck shop',
        description: 'Snacks, drinks and essentials.',
        meta: ['08:00 – 18:00', 'Residence lobby'],
        tags: ['Snacks'],
      },
    ],
  },
  sports: {
    description: 'Fitness classes, courts and membership.',
    items: [
      {
        id: 'spt-1',
        icon: icon(Dumbbell),
        title: 'Gym & weights room',
        description: 'Open access for all members.',
        meta: ['06:00 – 22:00', 'Sports Centre'],
        tags: ['Gym'],
        action: 'join',
        count: 340,
      },
      {
        id: 'spt-2',
        icon: icon(Volleyball),
        title: 'Badminton club',
        description: 'Weekly coached sessions on Sundays.',
        meta: ['Sun 09:00 – 11:00', 'Indoor courts'],
        tags: ['Club'],
        action: 'join',
        count: 87,
      },
      {
        id: 'spt-3',
        icon: icon(Flame),
        title: 'Group fitness classes',
        description: 'Spinning, yoga and HIIT each weekday.',
        meta: ['See schedule', 'Studio A'],
        tags: ['Classes'],
        action: 'interest',
        count: 152,
      },
      {
        id: 'spt-4',
        icon: icon(Bike),
        title: 'Cycling route & repair station',
        description: 'Campus bike parking and pump stand.',
        meta: ['Open 24/7', 'North gate'],
        tags: ['Outdoor'],
        action: 'book',
        count: 14,
      },
    ],
  },
  library: {
    description: 'Spaces, loans and services at the university library.',
    items: [
      {
        id: 'lib-1',
        icon: icon(Library),
        title: 'Main reading room',
        description: 'Quiet study, 400 seats with power outlets.',
        meta: ['07:30 – 23:00', 'Level 1'],
        tags: ['Study'],
        action: 'book',
        count: 64,
      },
      {
        id: 'lib-2',
        icon: icon(Laptop),
        title: 'Group study pods',
        description: 'Wheelchair-friendly pods for 4–6 people.',
        meta: ['Book in advance', 'Level 2'],
        tags: ['Group'],
        action: 'book',
        count: 31,
      },
      {
        id: 'lib-3',
        icon: icon(BookCopy),
        title: 'Course reserves',
        description: 'Short-loan copies of core textbooks.',
        meta: ['2 h loan', 'Help desk'],
        tags: ['Loans'],
        action: 'save',
      },
      {
        id: 'lib-4',
        icon: icon(QrCode),
        title: 'Self-service kiosks',
        description: 'Borrow and return books without queuing.',
        meta: ['Open 24/7', 'Ground floor'],
        tags: ['Services'],
        action: 'save',
      },
    ],
  },
  printing: {
    description: 'Print stations, balance and upload options.',
    items: [
      {
        id: 'prt-1',
        icon: icon(Printer),
        title: 'Pay-as-you-go printing',
        description: 'A4/A3 mono & colour from any station.',
        meta: ['Rs 10 / page', 'Every block'],
        tags: ['Printing'],
        action: 'book',
        count: 25,
      },
      {
        id: 'prt-2',
        icon: icon(UploadCloud),
        title: 'Web print upload',
        description: 'Upload your document and release it at any printer.',
        meta: ['Online', 'QR release'],
        tags: ['Printing'],
        action: 'save',
      },
      {
        id: 'prt-3',
        icon: icon(Scissors),
        title: 'Scanning stations',
        description: 'Scan to email or USB, free for students.',
        meta: ['Library & IT suites', 'Free'],
        tags: ['Scanning'],
        action: 'save',
      },
    ],
  },
  lost_found_section: {
    description: 'Search for lost items or report one you have found.',
    report: {
      label: 'Report an item',
      title: 'Report a lost or found item',
      description: 'Describe the item and where it was seen.',
      itemLabel: 'Item name and location',
    },
    items: [
      {
        id: 'lf-1',
        icon: icon(Wallet),
        title: 'Black leather wallet',
        description: 'Bifold with a dark blue card slot.',
        meta: ['Found in CSE 101', 'Reported today'],
        tags: ['Found'],
        action: 'claim',
        count: 2,
      },
      {
        id: 'lf-2',
        icon: icon(KeyRound),
        title: 'Keyring with 3 keys',
        description: 'Silver ring, one tagged key.',
        meta: ['Lost near sports centre', 'Reported 2 days ago'],
        tags: ['Lost'],
        action: 'claim',
        count: 0,
      },
      {
        id: 'lf-3',
        icon: icon(Headphones),
        title: 'White wireless earbuds',
        description: 'Case with USB-C, initial "N".',
        meta: ['Found in library', 'Reported yesterday'],
        tags: ['Found'],
        action: 'claim',
        count: 4,
      },
      {
        id: 'lf-4',
        icon: icon(Glasses),
        title: 'Round-frame sunglasses',
        description: 'Black frame, mild use.',
        meta: ['Lost at main gate', 'Reported 3 days ago'],
        tags: ['Lost'],
        action: 'claim',
        count: 0,
      },
    ],
  },
  it_support: {
    description: 'Get help with Wi-Fi, accounts and portal issues.',
    report: {
      label: 'Raise a ticket',
      title: 'New IT support ticket',
      description: 'Tell us what is not working so we can fix it.',
      itemLabel: 'Describe the problem',
    },
    items: [
      {
        id: 'its-1',
        icon: icon(Wifi),
        title: 'Wi-Fi — eduroam setup',
        description: 'Configure eduroam on your phone or laptop.',
        meta: ['Guide + remote assist', 'Mon–Fri'],
        tags: ['Network'],
        action: 'request',
      },
      {
        id: 'its-2',
        icon: icon(Bug),
        title: 'Portal sign-in problems',
        description: 'Password reset and account lockouts.',
        meta: ['Self-service reset', 'Avg. 10 min'],
        tags: ['Account'],
        action: 'request',
      },
      {
        id: 'its-3',
        icon: icon(Monitor),
        title: 'Lab machine fault',
        description: 'Report broken hardware in the teaching labs.',
        meta: ['Raise a ticket', 'CSE/IT blocks'],
        tags: ['Hardware'],
        action: 'request',
      },
      {
        id: 'its-4',
        icon: icon(Router),
        title: 'Software requests',
        description: 'Ask for software installation in labs.',
        meta: ['5-day lead time', 'Self-admin'],
        tags: ['Software'],
        action: 'request',
      },
    ],
  },
  facilities: {
    description: 'Report maintenance issues around campus.',
    report: {
      label: 'Report a problem',
      title: 'Report a facility issue',
      description: 'Where is the issue and what did you notice?',
      itemLabel: 'Location and problem',
    },
    items: [
      {
        id: 'fac-1',
        icon: icon(AlertTriangle),
        title: 'AC not cooling in CSE 201',
        meta: ['CSE Block · Floor 2', 'Reported today'],
        tags: ['HVAC'],
        action: 'request',
      },
      {
        id: 'fac-2',
        icon: icon(Projector),
        title: 'Projector lamp blown in Hall B',
        meta: ['Main hall', 'Reported today'],
        tags: ['AV'],
        action: 'request',
      },
      {
        id: 'fac-3',
        icon: icon(Hammer),
        title: 'Loose handrail near Lab 3',
        meta: ['Science wing', 'Reported yesterday'],
        tags: ['Maintenance'],
        action: 'request',
      },
      {
        id: 'fac-4',
        icon: icon(Droplets),
        title: 'Leaking sink in cafeteria',
        meta: ['Student Centre, ground floor', 'Reported 2 days ago'],
        tags: ['Plumbing'],
        action: 'request',
      },
    ],
  },
  jobs: {
    description: 'Part-time work, internships and placements.',
    items: [
      {
        id: 'job-1',
        icon: icon(Briefcase),
        title: 'Campus ambassador',
        description: 'Promote events and help at open days.',
        meta: ['Part-time', 'Apply by Fri'],
        tags: ['On-campus'],
        action: 'interest',
        count: 48,
      },
      {
        id: 'job-2',
        icon: icon(Rocket),
        title: 'Software intern — WSO2',
        description: '6-month full-stack internship, 2nd years welcome.',
        meta: ['Internship', 'Hybrid'],
        tags: ['Tech'],
        action: 'save',
      },
      {
        id: 'job-3',
        icon: icon(ShoppingCart),
        title: 'Retail assistant — campus store',
        description: 'Evening shifts, hospitality experience a plus.',
        meta: ['Part-time', 'Flexible'],
        tags: ['On-campus'],
        action: 'interest',
        count: 22,
      },
      {
        id: 'job-4',
        icon: icon(Languages),
        title: 'Tutor — English for beginners',
        description: 'Teach conversational English to staff.',
        meta: ['Part-time', '2 sessions/wk'],
        tags: ['Teaching'],
        action: 'interest',
        count: 31,
      },
    ],
  },
  financial_support_section: {
    description: 'Scholarships, bursaries and fee payment help.',
    items: [
      {
        id: 'fin-1',
        icon: icon(Award),
        title: 'Merit scholarship',
        description: 'For students achieving a GPA of 3.7+ in the last term.',
        meta: ['Value: Rs 250,000', 'Apply by 30 Sep'],
        tags: ['Scholarship'],
        action: 'request',
      },
      {
        id: 'fin-2',
        icon: icon(HandHeart),
        title: 'Hardship bursary',
        description: 'One-off support for unexpected financial difficulty.',
        meta: ['Means-tested', 'Year-round'],
        tags: ['Bursary'],
        action: 'request',
      },
      {
        id: 'fin-3',
        icon: icon(Banknote),
        title: 'Fee payment plans',
        description: 'Split your tuition into monthly instalments.',
        meta: ['From 3 instalments', 'SRI funds'],
        tags: ['Fees'],
        action: 'request',
      },
      {
        id: 'fin-4',
        icon: icon(Wallet),
        title: 'Emergency loan',
        description: 'Short-term, interest-free loans for essential needs.',
        meta: ['Up to Rs 50,000', 'Repay in 90 days'],
        tags: ['Support'],
        action: 'request',
      },
    ],
  },
  wellbeing_section: {
    description: 'Confidential support for your mental health and wellbeing.',
    items: [
      {
        id: 'wb-1',
        icon: icon(HeartPulse),
        title: 'Counselling service',
        description: 'Confidential one-to-one sessions with a counsellor.',
        meta: ['Book a slot', '20-min sessions'],
        tags: ['Counselling'],
        action: 'book',
      },
      {
        id: 'wb-2',
        icon: icon(Phone),
        title: '24/7 support line',
        description: 'Speak to someone any time, any day.',
        meta: ['0800 123 456', 'Free from campus'],
        tags: ['Urgent'],
        action: 'save',
      },
      {
        id: 'wb-3',
        icon: icon(Coffee),
        title: 'Peer support café',
        description: 'Drop-in coffee and chat with trained peers.',
        meta: ['Thu 12:00 – 14:00', 'Student Centre'],
        tags: ['Peer support'],
        action: 'interest',
        count: 60,
      },
      {
        id: 'wb-4',
        icon: icon(Sparkles),
        title: 'Mindfulness sessions',
        description: 'Weekly guided meditation for stress relief.',
        meta: ['Wed 08:00', 'Wellbeing room'],
        tags: ['Workshops'],
        action: 'book',
      },
    ],
  },

  /* ---------------------------- Student life ---------------------------- */
  societies: {
    description: 'Join clubs and societies that match your interests.',
    items: [
      {
        id: 'soc-cs',
        icon: icon(Monitor),
        title: 'Computer Science Society',
        description: 'Hackathons, tech talks and networking.',
        meta: ['420 members', 'Weekly meetups'],
        tags: ['Tech'],
        action: 'join',
        count: 420,
      },
      {
        id: 'soc-drama',
        icon: icon(Drama),
        title: 'Drama Society',
        description: 'Theatre production, improv and workshops.',
        meta: ['180 members', 'Auditions held'],
        tags: ['Arts'],
        action: 'join',
        count: 180,
      },
      {
        id: 'soc-music',
        icon: icon(Music),
        title: 'Music & Choir',
        description: 'Bands, choir and open-mic nights.',
        meta: ['250 members', 'Weekly rehearsals'],
        tags: ['Arts'],
        action: 'join',
        count: 250,
      },
      {
        id: 'soc-sports',
        icon: icon(Volleyball),
        title: 'Sports & Recreation',
        description: 'Organised leagues for badminton, cricket, football.',
        meta: ['390 members', 'Seasonal trials'],
        tags: ['Sports'],
        action: 'join',
        count: 390,
      },
      {
        id: 'soc-vol',
        icon: icon(HandHeart),
        title: 'Volunteering Society',
        description: 'Community projects and fundraisers.',
        meta: ['140 members', 'Monthly drives'],
        tags: ['Impact'],
        action: 'join',
        count: 140,
      },
    ],
  },
  events: {
    description: 'Upcoming events across campus — register your interest.',
    items: [
      {
        id: 'evt-1',
        icon: icon(Ticket),
        title: 'Careers & Internship Fair',
        description: 'Meet 40+ employers and land your next role.',
        meta: ['28 Sep · 10:00 – 16:00', 'Main Auditorium'],
        tags: ['Careers'],
        action: 'interest',
        count: 312,
      },
      {
        id: 'evt-2',
        icon: icon(Mic2),
        title: 'Guest lecture — AI ethics',
        description: 'Dr. Priya Perera discusses responsible AI.',
        meta: ['01 Oct · 15:00', 'CSE 101 (also on Zoom)'],
        tags: ['Lecture'],
        action: 'interest',
        count: 96,
      },
      {
        id: 'evt-3',
        icon: icon(Gamepad2),
        title: 'Hackathon 2026',
        description: '48 hours of building with the CS society.',
        meta: ['14–16 Oct', 'Innovation Hub'],
        tags: ['Competition'],
        action: 'interest',
        count: 204,
      },
      {
        id: 'evt-4',
        icon: icon(Music),
        title: 'Open-mic night',
        description: 'Perform, listen or cheer on friends.',
        meta: ['Fri 20:00', 'Student Centre'],
        tags: ['Social'],
        action: 'interest',
        count: 148,
      },
    ],
  },
  wellbeing2: {
    description: 'Campus events related to health and wellbeing.',
    items: [
      {
        id: 'wb-ev-1',
        icon: icon(Heart),
        title: 'Wellbeing week 2026',
        description: 'Free yoga, talks and drop-in counselling.',
        meta: ['Week of 23 Oct'],
        tags: ['Wellbeing'],
        action: 'interest',
        count: 240,
      },
      {
        id: 'wb-ev-2',
        icon: icon(Stethoscope),
        title: 'Health screening day',
        description: 'Blood pressure, glucose and BMI checks.',
        meta: ['12 Oct · 09:00 – 15:00', 'Health Centre'],
        tags: ['Health'],
        action: 'book',
      },
      {
        id: 'wb-ev-3',
        icon: icon(Presentation),
        title: 'Exam stress workshop',
        description: 'Practical techniques to manage exam pressure.',
        meta: ['15 Oct · 14:00', 'Wellbeing room'],
        tags: ['Workshop'],
        action: 'interest',
        count: 88,
      },
    ],
  },
  volunteering: {
    description: 'Give back with community volunteering opportunities.',
    items: [
      {
        id: 'vol-1',
        icon: icon(HandHeart),
        title: 'Weekend beach cleanup',
        description: 'Join the eco club for a coastal cleanup.',
        meta: ['Sun 08:00 – 12:00', 'Transport provided'],
        tags: ['Environment'],
        action: 'join',
        count: 45,
      },
      {
        id: 'vol-2',
        icon: icon(BookOpen),
        title: 'After-school tutoring',
        description: 'Help local schoolchildren with maths & English.',
        meta: ['Tue & Thu 15:30', 'Community centre'],
        tags: ['Education'],
        action: 'join',
        count: 32,
      },
      {
        id: 'vol-3',
        icon: icon(Building2),
        title: 'Blood donation drive',
        description: 'Host a donation day at the campus clinic.',
        meta: ['Sign-up roster', 'Health centre'],
        tags: ['Health'],
        action: 'interest',
        count: 90,
      },
    ],
  },
  onboarding: {
    description: 'Everything you need for your first weeks at university.',
    items: [
      {
        id: 'ob-1',
        icon: icon(Flag),
        title: 'Welcome week schedule',
        description: 'Tours, registration help and social events.',
        meta: ['Starts 30 Sep', 'All campuses'],
        tags: ['New students'],
        action: 'save',
      },
      {
        id: 'ob-2',
        icon: icon(KeyRound),
        title: 'Set up your account',
        description: 'Student ID, email and Wi-Fi in 20 minutes.',
        meta: ['Self-service', 'IT help onsite'],
        tags: ['Setup'],
        action: 'save',
      },
      {
        id: 'ob-3',
        icon: icon(BookMarked),
        title: 'Campus map & tour',
        description: 'Find lecture halls, libraries and services.',
        meta: ['Interactive map', 'Physical copies too'],
        tags: ['Guide'],
        action: 'save',
      },
      {
        id: 'ob-4',
        icon: icon(Users),
        title: 'Meet your faculty',
        description: 'Intro sessions with your department.',
        meta: ['Week 1', 'By department'],
        tags: ['Welcome'],
        action: 'interest',
        count: 115,
      },
    ],
  },
  highlights: {
    description: 'Recent achievements and moments from student life.',
    items: [
      {
        id: 'hl-1',
        icon: icon(Trophy),
        title: 'Design team wins national award',
        description: 'UCL student team took first place at the National Design Expo.',
        meta: ['Featured 2 days ago'],
        tags: ['Awards'],
      },
      {
        id: 'hl-2',
        icon: icon(Camera),
        title: 'Culture week highlights',
        description: 'Relive dances, food stalls and the talent show.',
        meta: ['Photo gallery'],
        tags: ['Culture'],
      },
      {
        id: 'hl-3',
        icon: icon(Star),
        title: 'Athletics team — unbeaten season',
        description: 'Badminton team returns champions after an unbeaten run.',
        meta: ['Sports'],
        tags: ['Achievements'],
      },
      {
        id: 'hl-4',
        icon: icon(Megaphone),
        title: 'Student entrepreneurs showcase',
        description: 'Startups from our summer incubator pitch their ideas.',
        meta: ['Innovation hub'],
        tags: ['Innovation'],
      },
    ],
  },
  alumni: {
    description: 'Stories, events and mentoring from UCL alumni.',
    items: [
      {
        id: 'al-1',
        icon: icon(Users),
        title: 'Alumni mentoring program',
        description: 'Pair up with a graduate in your field.',
        meta: ['Apply this term'],
        tags: ['Mentoring'],
        action: 'interest',
        count: 76,
      },
      {
        id: 'al-2',
        icon: icon(Briefcase),
        title: 'Alumni career talks',
        description: 'Monthly talks on breaking into tech, finance and design.',
        meta: ['First Tue of month'],
        tags: ['Careers'],
        action: 'interest',
        count: 54,
      },
    ],
  },
  guest_lectures_section: {
    description: 'Special lectures by visiting experts.',
    items: [
      {
        id: 'gl-1',
        icon: icon(Presentation),
        title: 'AI ethics in practice',
        description: 'Dr. Priya Perera, industry leader in responsible AI.',
        meta: ['01 Oct · 15:00', 'CSE 101 + Zoom'],
        tags: ['Lecture'],
        action: 'interest',
        count: 96,
      },
      {
        id: 'gl-2',
        icon: icon(Projector),
        title: 'Building products users love',
        description: 'Guest lecture by the VP of product at a leading SaaS.',
        meta: ['08 Oct · 14:00', 'Main Auditorium'],
        tags: ['Lecture'],
        action: 'interest',
        count: 120,
      },
    ],
  },
  schedule_changes: {
    description: 'Recent changes to classes and rooms.',
    items: [
      {
        id: 'sc-1',
        icon: icon(AlarmClock),
        title: 'DSA session moved',
        description: 'Wednesday tutorial moves from CSE 305 to CSE 202.',
        meta: ['This Wednesday'],
        tags: ['Room change'],
      },
      {
        id: 'sc-2',
        icon: icon(CalendarDays),
        title: 'Lab rescheduled',
        description: 'Database lab moves to 11:15 with the other group.',
        meta: ['Next Tuesday'],
        tags: ['Time change'],
      },
      {
        id: 'sc-3',
        icon: icon(CircleAlert),
        title: 'Guest lecture cancelled',
        description: 'The careers talk will be re-booked for next month.',
        meta: ['Cancelled'],
        tags: ['Cancellation'],
      },
    ],
  },
  feedback: {
    description: 'Module feedback and student surveys.',
    items: [
      {
        id: 'fb-1',
        icon: icon(ClipboardList),
        title: 'Mid-semester module survey',
        description: 'Help improve SEF, DBS and DSA this term.',
        meta: ['Closes 30 Sep', 'Anonymous'],
        tags: ['Survey'],
        action: 'request',
      },
      {
        id: 'fb-2',
        icon: icon(Star),
        title: 'Rate your lecturers',
        description: 'Feedback that feeds into teaching reviews.',
        meta: ['One per module'],
        tags: ['Survey'],
        action: 'request',
      },
    ],
  },
  it_support_alt: {
    description: 'Services and self-service tools for IT help.',
    report: {
      label: 'Raise a ticket',
      title: 'New IT support ticket',
      description: 'Tell us what is not working so we can fix it.',
      itemLabel: 'Describe the problem',
    },
    items: [
      {
        id: 'it-1',
        icon: icon(Wifi),
        title: 'eduroam & Wi-Fi',
        description: 'Guides, troubleshooting and remote assist.',
        meta: ['Mon–Fri'],
        tags: ['Network'],
      },
      {
        id: 'it-2',
        icon: icon(KeyRound),
        title: 'Reset your password',
        description: 'Self-service password reset with MFA.',
        meta: ['5 minutes'],
        tags: ['Account'],
      },
      {
        id: 'it-3',
        icon: icon(Printer),
        title: 'Printing & scanning help',
        description: 'Add credit, release jobs and find a station.',
        meta: ['Guides'],
        tags: ['Printing'],
      },
      {
        id: 'it-4',
        icon: icon(Smartphone),
        title: 'Install the portal app',
        description: 'Moodle, email and timetable on the go.',
        meta: ['iOS & Android'],
        tags: ['Mobile'],
      },
    ],
  },
  announcements: {
    description: 'Official updates from the university and your faculty.',
    items: [
      {
        id: 'ann-1',
        icon: icon(Megaphone),
        title: 'Exam timetables released',
        description: 'The final exam schedule for term 3 is now on the academic calendar.',
        meta: ['Academic Office', 'Today'],
        tags: ['Exams'],
      },
      {
        id: 'ann-2',
        icon: icon(UserCog),
        title: 'Student ID top-up hours',
        description: 'The ID office extends opening hours next week for new-enrolment card sets.',
        meta: ['Student Services', '2 days ago'],
        tags: ['Campus'],
      },
      {
        id: 'ann-3',
        icon: icon(CalendarDays),
        title: 'Foundation day – classes suspended',
        description: 'All lectures and labs are paused for the annual foundation day.',
        meta: ['Registry', '3 days ago'],
        tags: ['Calendar'],
      },
      {
        id: 'ann-4',
        icon: icon(Wifi),
        title: 'Planned network maintenance',
        description: 'Campus Wi-Fi briefly offline Sunday 02:00 – 04:00.',
        meta: ['IT Services', '1 week ago'],
        tags: ['IT'],
      },
    ],
  },
  users: {
    description: 'Accounts, verification status and access across the portal.',
    items: [
      {
        id: 'usr-1',
        icon: icon(UserRound),
        title: 'Student accounts',
        description: '3,120 active accounts · 42 pending verification.',
        meta: ['Registry'],
        tags: ['Students'],
        action: 'request',
      },
      {
        id: 'usr-2',
        icon: icon(UserCog),
        title: 'Staff & faculty',
        description: '210 academic and 95 administrative accounts.',
        meta: ['HR'],
        tags: ['Staff'],
        action: 'request',
      },
      {
        id: 'usr-3',
        icon: icon(UserRound),
        title: 'Parent access',
        description: 'Guardians may view finances and progress for their ward.',
        meta: ['Student Services'],
        tags: ['Parents'],
        action: 'request',
      },
      {
        id: 'usr-4',
        icon: icon(ShieldCheck),
        title: 'Access reviews',
        description: 'Quarterly review of role permissions and elevation requests.',
        meta: ['IT Security'],
        tags: ['Security'],
        action: 'request',
      },
    ],
  },
  progress: {
    description: 'Your ward&rsquo;s academic progress at a glance.',
    items: [
      {
        id: 'prg-1',
        icon: icon(TrendingUp),
        title: 'Cumulative GPA',
        description: '3.56 — improving for the third consecutive term.',
        meta: ['Term 3 · 2026'],
        tags: ['GPA'],
      },
      {
        id: 'prg-2',
        icon: icon(ClipboardCheck),
        title: 'Module completion',
        description: 'Completed 21 of 24 required credits this year.',
        meta: ['84% complete'],
        tags: ['Credits'],
      },
      {
        id: 'prg-3',
        icon: icon(Layers),
        title: 'Attendance',
        description: '94% across all enrolled modules this term.',
        meta: ['Excellent standing'],
        tags: ['Attendance'],
      },
      {
        id: 'prg-4',
        icon: icon(BarChart3),
        title: 'Faculty notes',
        description: 'Consistent effort in Databases; keep up the good work.',
        meta: ['Dr. Sanjaya Silva'],
        tags: ['Feedback'],
      },
    ],
  },
  fees: {
    description: 'Tuition, accommodation and payment plans for your ward.',
    items: [
      {
        id: 'fee-1',
        icon: icon(Wallet),
        title: 'Tuition – term 3',
        description: 'Rs 485,000 for the software engineering degree programme.',
        meta: ['Due 15 Oct', 'Scholarship applied'],
        tags: ['Tuition'],
        action: 'request',
      },
      {
        id: 'fee-2',
        icon: icon(UserRound),
        title: 'Accommodation',
        description: 'Halls of residence – twin sharing with meals.',
        meta: ['Rs 60,000 / term', 'Paid 01 Aug'],
        tags: ['Housing'],
        action: 'request',
      },
      {
        id: 'fee-3',
        icon: icon(Banknote),
        title: 'Payment plans',
        description: 'Split tuition into 3 monthly instalments at no interest.',
        meta: ['Eligible', 'SRI funds'],
        tags: ['Plans'],
        action: 'request',
      },
      {
        id: 'fee-4',
        icon: icon(BadgeCheck),
        title: 'Scholarships & aid',
        description: 'Merit award maintained — automatic renewal this term.',
        meta: ['Rs 250,000 credited'],
        tags: ['Scholarship'],
        action: 'request',
      },
    ],
  },
  timetable: {
    description: 'The weekly class schedule for your ward.',
    items: [
      {
        id: 'tt-1',
        icon: icon(AlarmClock),
        title: 'Monday – Software Engineering',
        description: 'Lecture · CSE 101',
        meta: ['09:00 – 10:30', 'Dr. Sanjaya Silva'],
        tags: ['Lecture'],
      },
      {
        id: 'tt-2',
        icon: icon(FlaskConical),
        title: 'Tuesday – Database Systems Lab',
        description: 'Lab · Lab 4',
        meta: ['11:00 – 12:30', 'Ms. Tharushi Weerasinghe'],
        tags: ['Lab'],
      },
      {
        id: 'tt-3',
        icon: icon(ClipboardList),
        title: 'Wednesday – Data Structures',
        description: 'Tutorial · CSE 305',
        meta: ['13:30 – 15:00', 'Dr. Kasun Jayasuriya'],
        tags: ['Tutorial'],
      },
      {
        id: 'tt-4',
        icon: icon(Users),
        title: 'Thursday – Group project workshop',
        description: 'Workshop · Innovation Hub',
        meta: ['10:00 – 12:00', 'Facilitated'],
        tags: ['Workshop'],
      },
      {
        id: 'tt-5',
        icon: icon(Monitor),
        title: 'Friday – Free study period',
        description: 'No scheduled sessions.',
        meta: ['Full day'],
        tags: ['Study'],
      },
    ],
  },
  grades: {
    description: 'Assessment results and reports for your ward.',
    items: [
      {
        id: 'gr-1',
        icon: icon(ClipboardCheck),
        title: 'Software Engineering – A-',
        description: 'Assignment + exam blend for CSE2201.',
        meta: ['Term 3 · 2026'],
        tags: ['CSE2201'],
      },
      {
        id: 'gr-2',
        icon: icon(ClipboardCheck),
        title: 'Database Systems – A',
        description: 'Top of cohort for the lab project.',
        meta: ['Term 3 · 2026'],
        tags: ['CSE2202'],
      },
      {
        id: 'gr-3',
        icon: icon(ClipboardList),
        title: 'Data Structures – B+',
        description: 'Solid theory paper, strong trace questions.',
        meta: ['Term 3 · 2026'],
        tags: ['CSE2203'],
      },
      {
        id: 'gr-4',
        icon: icon(FileBarChart),
        title: 'Term 3 report',
        description: 'Download the full academic report (PDF).',
        meta: ['Registry', 'PDF'],
        tags: ['Report'],
        action: 'save',
      },
    ],
  },

  /* ------------------------- Support & guidance ------------------------- */
  academic_support: {
    description: 'Study groups, peer tutoring and mentorship — ask for help early.',
    report: {
      label: 'Request support',
      title: 'Request academic support',
      description: 'Tell us the module and the kind of help you need.',
      itemLabel: 'Module and support needed',
    },
    items: [
      {
        id: 'as-1',
        icon: icon(Users),
        title: 'Study group matching',
        description: 'Get paired with classmates studying the same modules.',
        meta: ['Groups of 3–6', 'Matched weekly'],
        tags: ['Study groups'],
        action: 'join',
        count: 128,
      },
      {
        id: 'as-2',
        icon: icon(GraduationCap),
        title: 'Peer tutoring',
        description: 'One-to-one sessions with trained senior students.',
        meta: ['Free', 'Book 45-min slots'],
        tags: ['Tutoring'],
        action: 'request',
      },
      {
        id: 'as-3',
        icon: icon(Star),
        title: 'Staff mentorship',
        description: 'Longer-term guidance from an academic mentor in your field.',
        meta: ['Term-long', 'Apply with a short note'],
        tags: ['Mentorship'],
        action: 'request',
      },
      {
        id: 'as-4',
        icon: icon(BookOpen),
        title: 'Academic writing clinic',
        description: 'Feedback on essays, reports and referencing.',
        meta: ['Wed 14:00 – 16:00', 'Library, Level 2'],
        tags: ['Skills'],
        action: 'book',
        count: 22,
      },
    ],
  },
  faq: {
    description: 'Quick answers to the questions students ask most.',
    items: [
      {
        id: 'faq-1',
        icon: icon(KeyRound),
        title: 'How do I reset my portal password?',
        description:
          'Use the “Forgot password” link on the sign-in screen. A reset link is emailed to your university address and expires after 30 minutes.',
        meta: ['Account'],
        tags: ['Account'],
      },
      {
        id: 'faq-2',
        icon: icon(Library),
        title: 'What are the library opening hours?',
        description:
          'The main reading room is open 07:30 – 23:00 daily, with self-service borrowing available 24/7 via the kiosks on the ground floor.',
        meta: ['Library'],
        tags: ['Library'],
      },
      {
        id: 'faq-3',
        icon: icon(DoorOpen),
        title: 'How do I book a study room?',
        description:
          'Open Campus Bookings, choose a day, select free slots in the grid and confirm. Requests are instant and need no admin approval.',
        meta: ['Bookings'],
        tags: ['Bookings'],
      },
      {
        id: 'faq-4',
        icon: icon(Wallet),
        title: 'How do I pay my semester fees?',
        description:
          'Fees and instalment plans are shown under Financial Support. Payments can be made by bank transfer or online card payment from the same page.',
        meta: ['Finance'],
        tags: ['Fees'],
      },
      {
        id: 'faq-5',
        icon: icon(Wifi),
        title: 'Who do I contact about Wi-Fi or login problems?',
        description:
          'Raise a ticket in IT & Tech Support, or visit the helpdesk on the ground floor of the CSE Block (Mon–Fri, 08:00 – 18:00).',
        meta: ['IT'],
        tags: ['IT'],
      },
      {
        id: 'faq-6',
        icon: icon(HeartPulse),
        title: 'How do I access wellbeing support?',
        description:
          'The Wellbeing & Care section lists counselling, drop-in and 24/7 phone support. Counselling sessions are confidential and free.',
        meta: ['Wellbeing'],
        tags: ['Wellbeing'],
      },
    ],
  },
  academic_calendar: {
    description: 'Key dates, deadlines and semester milestones for the year ahead.',
    items: [
      {
        id: 'cal-1',
        icon: icon(CalendarDays),
        title: 'Semester 2 add/drop closes',
        description: 'Final day to add or withdraw from modules without a fee penalty.',
        meta: ['Fri, 29 Sep', 'Registry'],
        tags: ['Deadline'],
      },
      {
        id: 'cal-2',
        icon: icon(CalendarRange),
        title: 'Mid-semester break',
        description: 'No lectures or labs. Campus services remain open.',
        meta: ['23 – 27 Oct', 'All campuses'],
        tags: ['Break'],
      },
      {
        id: 'cal-3',
        icon: icon(CalendarDays),
        title: 'Final exam timetable published',
        description: 'Check your personalised exam schedule on the portal.',
        meta: ['Released 06 Nov', 'Academic Office'],
        tags: ['Exams'],
      },
      {
        id: 'cal-4',
        icon: icon(AlarmClock),
        title: 'Semester 2 examinations begin',
        description: 'Two-week examination period across all faculties.',
        meta: ['20 Nov – 01 Dec', 'Exam halls'],
        tags: ['Exams'],
      },
      {
        id: 'cal-5',
        icon: icon(BadgeCheck),
        title: 'Results release',
        description: 'Provisional results and transcripts available on the portal.',
        meta: ['Fri, 15 Dec', 'Registry'],
        tags: ['Results'],
      },
    ],
  },
  emergency: {
    description: 'Safety and emergency information — know what to do before you need it.',
    items: [
      {
        id: 'em-1',
        icon: icon(ShieldAlert),
        title: 'Campus emergency line',
        description: '24/7 security control room for urgent incidents on campus.',
        meta: ['+94 11 700 0000', 'Available 24/7'],
        tags: ['Urgent'],
        action: 'save',
      },
      {
        id: 'em-2',
        icon: icon(Flame),
        title: 'Fire evacuation procedure',
        description:
          'On hearing the alarm, leave by the nearest marked exit, use the stairs, and report to the assembly point at the front lawn.',
        meta: ['All buildings', 'Do not use lifts'],
        tags: ['Fire'],
        action: 'save',
      },
      {
        id: 'em-3',
        icon: icon(Stethoscope),
        title: 'Medical emergency',
        description: 'Campus clinic and first-aid rooms, plus guidance for calling an ambulance.',
        meta: ['Health Centre', 'Ground floor'],
        tags: ['Medical'],
        action: 'save',
      },
      {
        id: 'em-4',
        icon: icon(CircleAlert),
        title: 'Report a safety concern',
        description: 'Flag lighting, hazards or suspicious activity to security.',
        meta: ['Confidential', 'Reviewed daily'],
        tags: ['Report'],
        action: 'request',
      },
      {
        id: 'em-5',
        icon: icon(Phone),
        title: 'Emergency contacts',
        description: 'Police, ambulance, fire and the UCL security duty officer.',
        meta: ['119 / 110 / 1990', 'Save to phone'],
        tags: ['Contacts'],
        action: 'save',
      },
    ],
  },
  staff_directory: {
    description: 'Find the right person or department for your query.',
    items: [
      {
        id: 'dir-1',
        icon: icon(GraduationCap),
        title: 'Academic Office',
        description: 'Module registration, timetables and assessment queries.',
        meta: ['academics@ucl.ac.lk', 'CSE Block, Floor 1 · Ext 4100'],
        tags: ['Academic'],
      },
      {
        id: 'dir-2',
        icon: icon(Wifi),
        title: 'IT Helpdesk',
        description: 'Accounts, Wi-Fi, printing and portal technical support.',
        meta: ['it.support@ucl.ac.lk', 'Ext 4200 · Mon–Fri 08:00–18:00'],
        tags: ['IT'],
      },
      {
        id: 'dir-3',
        icon: icon(UserRound),
        title: 'Student Services & Registry',
        description: ' enrolment, ID cards, letters and student records.',
        meta: ['students@ucl.ac.lk', 'Student Centre, Ground floor'],
        tags: ['Registry'],
      },
      {
        id: 'dir-4',
        icon: icon(Banknote),
        title: 'Finance Office',
        description: 'Fees, invoices, refunds and payment plans.',
        meta: ['finance@ucl.ac.lk', 'Ext 4300 · Mon–Fri 09:00–16:00'],
        tags: ['Finance'],
      },
      {
        id: 'dir-5',
        icon: icon(HeartPulse),
        title: 'Wellbeing & Counselling',
        description: 'Confidential mental-health and pastoral support.',
        meta: ['wellbeing@ucl.ac.lk', 'Health Centre · Ext 4400'],
        tags: ['Wellbeing'],
      },
      {
        id: 'dir-6',
        icon: icon(Library),
        title: 'Library Services',
        description: 'Loans, reserves, research help and study spaces.',
        meta: ['library@ucl.ac.lk', 'Level 1 help desk'],
        tags: ['Library'],
      },
    ],
  },
  textbooks: {
    description: 'Buy, swap or pass on second-hand textbooks and study materials.',
    report: {
      label: 'List a textbook',
      title: 'List a textbook for exchange',
      description: 'Add the title, condition and a way to reach you.',
      itemLabel: 'Book title and condition',
    },
    items: [
      {
        id: 'tb-1',
        icon: icon(BookCopy),
        title: 'Clean Code — Robert C. Martin',
        description: 'Good condition, light highlighting in chapters 2–4.',
        meta: ['Available', 'Rs 2,500 or swap'],
        tags: ['Available'],
        action: 'claim',
        count: 3,
      },
      {
        id: 'tb-2',
        icon: icon(BookMarked),
        title: 'Introduction to Algorithms (CLRS)',
        description: 'Wanted — 3rd edition for Data Structures next term.',
        meta: ['Wanted', 'Will swap or buy'],
        tags: ['Wanted'],
        action: 'interest',
        count: 5,
      },
      {
        id: 'tb-3',
        icon: icon(Database),
        title: 'Database System Concepts',
        description: '7th edition, minimal wear, no notes.',
        meta: ['Available', 'Rs 3,200'],
        tags: ['Available'],
        action: 'claim',
        count: 1,
      },
      {
        id: 'tb-4',
        icon: icon(Layers),
        title: 'Operating System Concepts',
        description: 'Wanted for the OS elective — any recent edition.',
        meta: ['Wanted', 'Campus pickup'],
        tags: ['Wanted'],
        action: 'interest',
        count: 2,
      },
    ],
  },
};

// Compact alias for slugs that are long or awkward to reference.
export const SECTION_ALIASES: Record<string, string> = {
  'lost-found': 'lost_found_section',
  'financial-support': 'financial_support_section',
  wellbeing: 'wellbeing_section',
  wellbeing2: 'wellbeing_section',
  'guest-lectures': 'guest_lectures_section',
  'schedule-changes': 'schedule_changes',
  'academic-support': 'academic_support',
  'academic-calendar': 'academic_calendar',
  'staff-directory': 'staff_directory',
  'it-support': 'it_support_alt',
  onboarding: 'onboarding',
  highlights: 'highlights',
};

/** Canonical lookup that resolves nav slugs (e.g. `/portal/events`) to data. */
export function getSectionFeed(slug: string | undefined): SectionFeed | undefined {
  if (slug === undefined) return undefined;
  const key = SECTION_ALIASES[slug] ?? slug;
  return SECTION_DATA[key];
}
